<a href="https://colab.research.google.com/github/Dheemant-12/CreditCardFraudDetection/blob/main/NumpyDocumentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])
a[0]
a[0]=0 #replacing an favourite element in the desired position
a # so array becomes 0,2,3,4,5
a[:3] #produces first 3 elements
b=a[3:] # starts from 3rd and ends at last syntax: a[start:stop:step]
b
b[0]=35 # the new b becomes [4,5], now after changing it becomes [35,5]
a,b


(array([ 0,  2,  3, 35,  5]), array([35,  5]))

###Array attributes

In [4]:
#ndim means the dimensions of the array
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a.ndim # this specifies the dimensions of array
a.shape #this specifies the shape of matrix
a.size # Total number of elements present in the matrix


12

###How to create a Basic Array

In [5]:
np.zeros(5) # used fror creating an array filled with zeros
np.ones(3) # similarly for ones also
np.empty(8) # this fills the array with most random numbers which doesnt usually change
np.arange(5) # used to make an array from range
np.arange(2,10,2) # syntax a(start,stop,step) , always start is included but end number is not included in output
np.linspace(0,10,num=5) #You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval
np.ones(2,dtype=np.int64) # we can use np.float64 also

array([1, 1])

###Adding, removing, and sorting elements and concatenating


In [6]:
arr=np.array([10,3,45,57,8])
np.sort(arr)#for ascending order
np.argsort(arr) # array([1, 4, 0, 2, 3])
#lexsort prints alphabetically and returns indices
first_names = ['Charlie', 'Alice', 'Bob']
surnames = ['Smith', 'Smith', 'Jones']
indices = np.lexsort((first_names, surnames))
print(indices)  # Output: [2, 1, 0]
#searchsorted
sorted_arr = np.array([10, 20, 30, 40])
index = np.searchsorted(sorted_arr, 25)
print(index)  # Output: 2
#partial
arr = np.array([90, 10, 50, 20, 80])
partitioned = np.partition(arr, 2)
print(partitioned)  # Output: [20, 10, 50, 90, 80]
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.concatenate((a,b),axis=0)#concatenation which means combining 2 arrays together

[2 1 0]
2
[10 20 50 80 90]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
arr_example=np.array([[[0,1,2,3],
                       [4,5,6,7]],
                       [[0,1,2,3],
                        [4,5,6,7]],
                      [[0,1,2,3],
                       [4,5,6,7]]])
arr_example.ndim
arr_example.size
arr_example.shape

(3, 2, 4)

In [14]:
a = np.arange(6)
print(a)
b = a.reshape(3, 2)
print(b)
np.reshape(a, (1, 6), order='C')

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


array([[0, 1, 2, 3, 4, 5]])

## COnverting 1D array to 2D Array


In [16]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [19]:
a2=a[np.newaxis,:] #we can use np.newaxis to convert 1d to 2d and so on
a2.shape

(1, 6)

In [21]:
row_vector=a[np.newaxis,:]
row_vector.shape
col_vector=a[:,np.newaxis]
col_vector.shape

(6, 1)

In [23]:
b = np.expand_dims(a, axis=1)
b.shape
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

### Indexing and Slicing

In [26]:
data=np.array([1,2,3])
data[1]
data[0:2]
data[1:]
data[-2:]

array([2, 3])

In [29]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])
five_up = (a >= 5)
print(a[five_up])
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[1 2 3 4]
[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]


In [34]:
c = a[(a > 2) & (a < 11)]
print(c)
five_up = (a > 5) | (a == 5)
print(five_up)
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 5)
print(b)
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)
    not_there = np.nonzero(a == 42)
print(not_there)

[ 3  4  5  6  7  8  9 10]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
(array([0, 0, 0, 0]), array([0, 1, 2, 3]))
(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))
(array([], dtype=int64), array([], dtype=int64))
