<a href="https://colab.research.google.com/github/Dheemant-12/CreditCardFraudDetection/blob/main/NumpyDocumentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [10]:
a=np.array([1,2,3,4,5])
a[0]
a[0]=0 #replacing an favourite element in the desired position
a # so array becomes 0,2,3,4,5
a[:3] #produces first 3 elements
b=a[3:] # starts from 3rd and ends at last syntax: a[start:stop:step]
b
b[0]=35 # the new b becomes [4,5], now after changing it becomes [35,5]
a,b


(array([ 0,  2,  3, 35,  5]), array([35,  5]))

###Array attributes

In [20]:
#ndim means the dimensions of the array
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a.ndim # this specifies the dimensions of array
a.shape #this specifies the shape of matrix
a.size # Total number of elements present in the matrix


12

###How to create a Basic Array

In [35]:
np.zeros(5) # used fror creating an array filled with zeros
np.ones(3) # similarly for ones also
np.empty(8) # this fills the array with most random numbers which doesnt usually change
np.arange(5) # used to make an array from range
np.arange(2,10,2) # syntax a(start,stop,step) , always start is included but end number is not included in output
np.linspace(0,10,num=5) #You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval
np.ones(2,dtype=np.int64) # we can use np.float64 also

array([1, 1])

###Adding, removing, and sorting elements and concatenating
:

In [45]:
arr=np.array([10,3,45,57,8])
np.sort(arr)#for ascending order
np.argsort(arr) # array([1, 4, 0, 2, 3])
#lexsort prints alphabetically and returns indices
first_names = ['Charlie', 'Alice', 'Bob']
surnames = ['Smith', 'Smith', 'Jones']
indices = np.lexsort((first_names, surnames))
print(indices)  # Output: [2, 1, 0]
#searchsorted
sorted_arr = np.array([10, 20, 30, 40])
index = np.searchsorted(sorted_arr, 25)
print(index)  # Output: 2
#partial
arr = np.array([90, 10, 50, 20, 80])
partitioned = np.partition(arr, 2)
print(partitioned)  # Output: [20, 10, 50, 90, 80]
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.concatenate((a,b),axis=0)#concatenation which means combining 2 arrays together

[2 1 0]
2
[10 20 50 80 90]


array([1, 2, 3, 4, 5, 6, 7, 8])